defmodule Lorito.Responses.Constants do
  @content_types [
    "text/html",
    "application/json",
    "text/plain",
    "application/xml",
    "application/x-www-form-urlencoded",
    "multipart/form-data",
    "text/css",
    "text/javascript",
    "application/javascript",
    "image/jpeg",
    "image/png",
    "image/gif",
    "image/svg+xml",
    "application/pdf",
    "audio/mpeg",
    "video/mp4",
    "application/octet-stream",
    "application/zip",
    "text/csv",
    "application/vnd.ms-excel",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/atom+xml",
    "application/rss+xml",
    "text/xml",
    "application/xhtml+xml",
    "font/woff",
    "font/woff2",
    "application/x-font-ttf",
    "application/ld+json",
    "text/calendar",
    "application/x-shockwave-flash",
    "image/webp",
    "audio/wav",
    "video/webm",
    "application/x-tar",
    "application/x-gzip",
    "application/x-bzip2",
    "application/epub+zip",
    "application/x-httpd-php",
    "application/sql",
    "application/graphql",
    "application/x-www-form-urlencoded",
    "application/x-pkcs12",
    "application/x-pkcs7-certificates",
    "application/x-pkcs7-mime",
    "application/x-pkcs7-signature",
    "application/vnd.android.package-archive",
    "application/vnd.apple.installer+xml"
  ]

  @http_codes [
    {100, "Continue"},
    {101, "Switching Protocols"},
    {102, "Processing"},
    {200, "OK"},
    {201, "Created"},
    {202, "Accepted"},
    {203, "Non-Authoritative Information"},
    {204, "No Content"},
    {205, "Reset Content"},
    {206, "Partial Content"},
    {207, "Multi-Status"},
    {208, "Already Reported"},
    {226, "IM Used"},
    {300, "Multiple Choices"},
    {301, "Moved Permanently"},
    {302, "Found"},
    {303, "See Other"},
    {304, "Not Modified"},
    {305, "Use Proxy"},
    {307, "Temporary Redirect"},
    {308, "Permanent Redirect"},
    {400, "Bad Request"},
    {401, "Unauthorized"},
    {402, "Payment Required"},
    {403, "Forbidden"},
    {404, "Not Found"},
    {405, "Method Not Allowed"},
    {406, "Not Acceptable"},
    {407, "Proxy Authentication Required"},
    {408, "Request Timeout"},
    {409, "Conflict"},
    {410, "Gone"},
    {411, "Length Required"},
    {412, "Precondition Failed"},
    {413, "Payload Too Large"},
    {414, "URI Too Long"},
    {415, "Unsupported Media Type"},
    {416, "Range Not Satisfiable"},
    {417, "Expectation Failed"},
    {418, "I'm a teapot"},
    {421, "Misdirected Request"},
    {422, "Unprocessable Entity"},
    {423, "Locked"},
    {424, "Failed Dependency"},
    {425, "Too Early"},
    {426, "Upgrade Required"},
    {428, "Precondition Required"},
    {429, "Too Many Requests"},
    {431, "Request Header Fields Too Large"},
    {451, "Unavailable For Legal Reasons"},
    {500, "Internal Server Error"},
    {501, "Not Implemented"},
    {502, "Bad Gateway"},
    {503, "Service Unavailable"},
    {504, "Gateway Timeout"},
    {505, "HTTP Workspace Not Supported"},
    {506, "Variant Also Negotiates"},
    {507, "Insufficient Storage"},
    {508, "Loop Detected"},
    {510, "Not Extended"},
    {511, "Network Authentication Required"}
  ]

  def content_types do
    @content_types
  end

  def http_codes do
    @http_codes
  end
end
