defmodule Lorito.Repo.Migrations.AddDnsLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:logs), to: table(:http_logs)

    create table(:dns_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :query_name, :text, null: false
      add :record_type, :text, null: false
      add :ip, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id,
          references(:workspaces,
            column: :id,
            name: "dns_logs_workspace_id_fkey",
            type: :text,
            prefix: "public"
          )

      add :project_id,
          references(:projects,
            column: :id,
            name: "dns_logs_project_id_fkey",
            type: :text,
            prefix: "public"
          )
    end

    execute("""
    CREATE OR REPLACE VIEW all_logs AS
      SELECT id, project_id, workspace_id, inserted_at, updated_at, 'http' AS protocol
      FROM http_logs

      UNION ALL

      SELECT id, project_id, workspace_id, inserted_at, updated_at, 'dns' AS protocol
      FROM dns_logs;
    """)
  end

  def down do
    execute("DROP VIEW IF EXISTS all_logs;")

    drop constraint(:dns_logs, "dns_logs_workspace_id_fkey")

    drop constraint(:dns_logs, "dns_logs_project_id_fkey")

    drop table(:dns_logs)

    rename table(:http_logs), to: table(:logs)
  end
end
