defmodule Lorito.Repo.Migrations.AddSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :data, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute """
    INSERT INTO settings (id, data, inserted_at, updated_at) VALUES (
      gen_random_uuid(),
      '{"dns_enabled":false,"dns_domain":"","dns_ipv4_address":"0.0.0.0","dns_ipv6_address":"::"}'::jsonb,
      now() AT TIME ZONE 'utc',
      now() AT TIME ZONE 'utc'
    )
    """
  end

  def down do
    drop table(:settings)
  end
end
