defmodule Lorito.Repo.Migrations.AddIndexesToWorkspace do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:workspaces, [:id, :project_id],
             name: "workspaces_unique_id_per_project_index"
           )

    create unique_index(:workspaces, [:path], name: "workspaces_unique_path_index")
  end

  def down do
    drop_if_exists unique_index(:workspaces, [:path], name: "workspaces_unique_path_index")

    drop_if_exists unique_index(:workspaces, [:id, :project_id],
                     name: "workspaces_unique_id_per_project_index"
                   )
  end
end
